version: "3.8"
services:
  mariadb:
    build: ./mariadb/
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db-data
        target: /data
#    restart: always
volumes:
  db-data:
